### ISSUE TITLE
Create Relaton flavor for ECMA

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ecma#1]
Since ECMA's website does not work well with dynamic search or listing, we may have to write a scrape script and a relaton-data-ecma repo to store bib items.

**Comment by andrew2net** [comment]
@ronaldtse do we need to the [previous editionds](https://www.ecma-international.org/publications/standards/Ecma-006-arch.htm) as a relation?

**Comment by ronaldtse** [comment]
Yes please. Thanks!

**Comment by andrew2net** [comment]
> Since ECMA's website does not work well with dynamic search or listing, we may have to write a scrape script and a relaton-data-ecma repo to store bib items.

@ronaldtse the website doesn't search well but it possible to get the documents by adding their refence to the endpoint https://www.ecma-international.org/publications/standards/

**Comment by ronaldtse** [comment]
@andrew2net I'd be more comfortable maintaining a static data source for the documents listed:
* https://www.ecma-international.org/publications/standards/Standard.htm
* https://www.ecma-international.org/publications/techreports/techrep.htm
* https://www.ecma-international.org/publications/memento_index.htm

?
