### ISSUE TITLE
Maintaining a static data source for ECMA publications

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ecma#2]
@andrew2net I'd be more comfortable maintaining a static data source for the documents listed:
* https://www.ecma-international.org/publications/standards/Standard.htm
* https://www.ecma-international.org/publications/techreports/techrep.htm
* https://www.ecma-international.org/publications/memento_index.htm

?

_Originally posted by @ronaldtse in https://github.com/relaton/relaton-ecma/issues/1#issuecomment-749646617_

**Comment by andrew2net** [comment]
@ronaldtse do you mean we need relaton-data-ecma repository with all the documents?


> * https://www.ecma-international.org/publications/standards/Standard.htm

These documents are avalable for fetching by the current relaton-ecma version.


> * https://www.ecma-international.org/publications/techreports/techrep.htm

This link redirects to the home page. Looks like the new link is https://www.ecma-international.org/publications-and-standards/technical-reports, isn't it?


> * https://www.ecma-international.org/publications/memento_index.htm

This link reidrects to the https://www.ecma-international.org/publications-and-standards/mementos page. It isn't clear for me what can we get from the page. It only contains list of dates and links to PDF files.

**Comment by ronaldtse** [comment]
> The above documents are avalable for fetching by the current relaton-ecma version.

OK, but I'm also concerned their website is very slow to fetch from. I think we should have a relaton-data-ecma that can be also fetched via one of:

- a GitHub repo cloned locally, like https://raw.githubusercontent.com/relaton/bib-ecma/
- a GitHub repo linked file, like https://raw.githubusercontent.com/relaton/bib-ecma/master/index.yaml
- a GitHub pages site, like relaton.github.io/bib-ecma/index.json

And this cache updates daily.

> This link redirects to the home page. Looks like the new link is https://www.ecma-international.org/publications-and-standards/technical-reports, isn't it?

Yes.

> This link redirects to the https://www.ecma-international.org/publications-and-standards/mementos page. It isn't clear for me what can we get from the page. It only contains list of dates and links to PDF files.

The document metadata for these files are:
- title: "Memento 2021" for year 2021
- publisher: "Ecma International"
- link: (the actual link)
