### ISSUE TITLE
(URGENT) Unable to fetch "ECMA-262"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ecma#7]
This exists but cannot be fetched.

https://www.ecma-international.org/publications-and-standards/standards/ecma-262/

We should also allow edition numbers:
<img width="445" alt="Screenshot 2023-04-13 at 10 37 42 AM" src="https://user-images.githubusercontent.com/11865/231633523-59b72da6-a3bb-413a-a030-80cc4e2ff368.png">

This is blocking:
* https://github.com/metanorma/iso-10303-2/issues/141

**Comment by andrew2net** [comment]
@ronaldtse there are also volumes, for example [ECMA-269](https://www.ecma-international.org/publications-and-standards/standards/ecma-269/)

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/5623890/234644047-87692c07-3b18-4b3c-a794-11ef8b743c3c.png">

I suggest to use references like `ECMA-269 e3 vol1`. The edition "e" and volume "vol" are optional. If edition is ommited then the latest edition should be found. If volume is ommited then the first volume should be found. Edition can have major an minor numbers (`ECMA-262 e5.1`). Is it ok?

**Comment by andrew2net** [comment]
fixed in v 1.14.1 https://github.com/relaton/relaton-ecma#fetch-documents

**Comment by ronaldtse** [comment]
> there are also volumes, for example [ECMA-269](https://www.ecma-international.org/publications-and-standards/standards/ecma-269/)
> 
> I suggest to use references like `ECMA-269 e3 vol1`. The edition "e" and volume "vol" are optional. If edition is ommited then the latest edition should be found. If volume is ommited then the first volume should be found. Edition can have major an minor numbers (`ECMA-262 e5.1`). Is it ok?

I agree. Thanks!
